add_rules("mode.debug", "mode.release")
set_languages("c++26")
set_encodings("utf-8")
add_files("src/*.cpp")
add_includedirs("include")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

target("gnu")
    set_kind("binary")
    set_toolchains("gcc")
    set_runtimes("stdc++_shared")
    add_linkdirs("/usr/local/lib/../lib64")
    add_rpathdirs("/usr/local/lib/../lib64")

target("llvm")
    set_kind("binary")
    set_toolchains("clang")
    set_runtimes("c++_shared")
    add_linkdirs("/usr/local/lib/x86_64-unknown-linux-gnu")
    add_rpathdirs("/usr/local/lib/x86_64-unknown-linux-gnu")
